name    'puppet-xen-vif-proxyarp'
version '0.1.0'
source 'git@github.com:stengah33/puppet-xen-vif-proxyarp.git'
author 'stengah33'
license 'Apache License, Version 2.0'
summary 'Puppet module enabling Proxy ARP vif mode in Xen'
description 'Puppet module enabling Proxy ARP vif mode in Xen'
project_page 'https://github.com/stengah33/puppet-xen-vif-proxyarp'

dependency 'jproyo/git', '>= 0.0.1'
dependency 'puppetlabs-stdlib', '>= 0.0.1'
